radicle-dev/heartwood

Cargo.lock
radicle-node/Cargo.toml
radicle-node/src/test/tests.rs
radicle-tools/Cargo.toml
radicle-tools/src/rad-init.rs
radicle/src/git.rs
radicle/src/identity/project.rs
radicle/src/rad.rs
radicle/src/storage.rs
radicle/src/storage/git.rs
radicle/src/test/arbitrary.rs
radicle/src/test/fixtures.rs

Lean on rust's type system to improve safety.

git: Use RefString types for git::refs

---

radicle-node/src/service/filter.rs
radicle-node/src/test/arbitrary.rs
radicle-node/src/wire.rs
radicle/src/test/arbitrary.rs

This should help small nodes waste less bandwidth, while standardizing on set sizes.

Add variable bloom filter sizes

---

Cargo.lock
radicle-tools/src/rad-push.rs
radicle/src/git.rs
radicle/src/identity/project.rs
radicle/src/rad.rs
radicle/src/storage.rs
radicle/src/storage/git.rs
radicle/src/storage/refs.rs
radicle/src/test/storage.rs

The previous iteration of the storage layout for projects organised peer's subtrees by the `refs/remotes` category. This layout leads to problems when linking a working copy to the storage project. The fetch refspec would look something like:
`fetch = +refs/remotes/abc/heads/*:refs/remotes/rad/*`
This works perfectly fine when running:
git fetch rad
but will fail when one tries to specify:
`git fetch rad main`
Instead, the command would need to be:
`git fetch remotes/abc/heads/main`
This patch proposes to move the use of `refs/namespaces` for each peer. The layout looks similar in that each peer has a subtree, but instead it is under `refs/namespaces/<peer>/refs/...`.
The previous refspec would look more familiar in its new form:
`fetch = +refs/heads/*:refs/remotes/rad/*`
With this in …

radicle: namespace peers

---

radicle/src/storage.rs

The `V` parameter of `Remote` is already determined by the `refs` field. The `verified: PhantomData<V>` field is not required.
Remove the `verified` field to simplify the `Remote` struct.
Fixes #40

radicle: remove verified field in Remote

---

radicle-ssh/src/agent/client.rs
radicle-ssh/src/encoding.rs
radicle-ssh/src/key.rs
radicle/src/ssh.rs

Armored signatures are used by Git for signing commits.  Support reading writing these signatures by implementing a new trait to read and write to the SSH format.

SSH: support encoding/decoding armored signatures

---

Cargo.lock
Cargo.toml
radicle/Cargo.toml
radicle/src/git.rs
radicle/src/storage/git.rs
radicle/src/storage/refs.rs

The `git-ref-format`[[0]] and `radicle-git-ext`[[1]] crates are now published to crates.io.
Switch the dependency to rely on them. This also required to update the `git2` dependency to `0.15.0` as well as using the `vendored-libgit2` feature -- avoiding the openssl dependency too.
Fixes #27 
[0]: https://crates.io/crates/git-ref-format
[1]: https://crates.io/crates/radicle-git-ext

radicle: depend on radicle-git published crates

---

Cargo.lock
Cargo.toml
radicle-remote-helper/Cargo.toml
radicle-remote-helper/src/git-remote-rad.rs
radicle-remote-helper/src/lib.rs
radicle-ssh/src/agent/client.rs
radicle/src/node.rs
radicle/src/profile.rs
radicle/src/rad.rs
radicle/src/storage/git.rs

This handles `rad://` remotes, by setting the namespace correctly.
I'm not sure how to test this yet... since I'd like to have `git-push` and `git-fetch` invoke it :thinking:, but I've tested it manually and it works.
Note that instead of verifying that the namespace matches a key in SSH-agent, we simply set the namespace to whatever the profile's public key is, unlike what the issue states.
Closes #32

Implement `git-remote-rad` helper

---

radicle-node/src/service.rs
radicle-node/src/service/message.rs
radicle-node/src/service/peer.rs
radicle-node/src/test/arbitrary.rs
radicle-node/src/test/peer.rs
radicle-node/src/test/tests.rs
radicle-node/src/wire/message.rs

Use pings to check connection health with network peers and drop them if they prove unresponsive.

Service: drop unresponsive peers

---

radicle-node/src/decoder.rs
radicle-node/src/lib.rs
radicle-node/src/service.rs
radicle-node/src/service/config.rs
radicle-node/src/service/message.rs
radicle-node/src/service/peer.rs
radicle-node/src/service/reactor.rs
radicle-node/src/test/arbitrary.rs
radicle-node/src/test/peer.rs
radicle-node/src/test/simulator.rs
radicle-node/src/wire/message.rs

This type that was wrapping `Message` isn't very useful here. If we decide that we do need something like that, it's best handled one layer below.

Remove `Envelope` type

---

radicle-remote-helper/src/lib.rs
radicle/src/git.rs
radicle/src/identity/project.rs
radicle/src/rad.rs
radicle/src/storage.rs
radicle/src/storage/git.rs
radicle/src/test/storage.rs

We set the `HEAD` and eg. `refs/heads/master` refs when updating repositories, which allows users to easily clone with git.
For now, `HEAD` is chosen based on a unanimity quorum of delegates. This can be made more sophisticated in the future.
We've also had to ignore some refs during verification, since these have cropped in for eg. due to the staging copy clone and the changes included here.

Set repository canonical refs

---

Cargo.lock
Cargo.toml
build.rs
radicle-httpd/Cargo.toml
radicle-httpd/src/error.rs
radicle-httpd/src/lib.rs
radicle-httpd/src/main.rs

Introduces a new `radicle-httpd` crate which will serve as the basis for heartwood's HTTP backend.
The first part of this is a git server which allows projects to be fetched from storage using plain `git`.
Most of this code was copied from `radicle-client-services/git-server`, and heavily stripped down.
Depends on #57 

httpd: implement `git` fetch-only server

---

radicle/src/node.rs

Correct radicle::node::Error::Connect's string.

radicle: fix error typo

---

Cargo.lock
Cargo.toml
radicle-crypto/Cargo.toml
radicle-crypto/src/lib.rs
radicle-crypto/src/ssh.rs
radicle-crypto/src/ssh/agent.rs
radicle-crypto/src/test.rs
radicle-crypto/src/test/arbitrary.rs
radicle-crypto/src/test/signer.rs
radicle-node/src/service/message.rs
radicle-node/src/test/gossip.rs
radicle-node/src/test/peer.rs
radicle-node/src/test/tests.rs
radicle-remote-helper/Cargo.toml
radicle-remote-helper/src/lib.rs
radicle-tools/src/rad-agent.rs
radicle-tools/src/rad-auth.rs
radicle-tools/src/rad-self.rs
radicle/Cargo.toml
radicle/src/git.rs
radicle/src/identity/project.rs
radicle/src/lib.rs
radicle/src/rad.rs
radicle/src/sql.rs
radicle/src/storage.rs
radicle/src/storage/git.rs
radicle/src/storage/refs.rs
radicle/src/test.rs
radicle/src/test/arbitrary.rs

The crypto types are useful to use in other components that are separate from the radicle crate, e.g. the incoming radicle-cobs crate.
Separate out the types into a radicle-crypto crate. This crate defines the usual PublicKey, SecretKey, and Signature types. It also provides the ssh functionality, under the `ssh` feature. It is also necessary to provide the `From` impl for `Component` here, which again is guarded by the `git-ref-format` feature.
The `Arbitrary` implementation are moved. The arbitrary decision of redefining `ByteArray` in both radicle-crypto and radicle was made.
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>
X-Clacks-Overhead: GNU Terry Pratchett

radicle-crypto: split out from radicle

---

radicle-tools/src/rad-auth.rs
radicle/src/keystore.rs
radicle/src/profile.rs

Instead of failing over when a key has been created, run as normal using the previously created profile.

rad-auth: allow running multiple times

---

radicle-node/src/service.rs
radicle-node/src/service/reactor.rs
radicle-node/src/service/session.rs
radicle-node/src/test/tests.rs

Rename the module to session from peer to be consistent with recent renaming of the type from Peer to Session.

node: follow up on session renaming

---

Cargo.lock
radicle-node/Cargo.toml
radicle-node/src/service.rs
radicle-node/src/service/message.rs
radicle-node/src/test/arbitrary.rs
radicle-node/src/test/peer.rs

We implement a small proof-of-work on the node announcement message to prevent the routing table from being filled by fake entries.
We choose `scrypt` for its memory-hard properties.
Closes #28 

node: implement node announcement sybil resistance

---

radicle-node/src/service.rs
radicle-node/src/service/session.rs

Make accessing an important session value, the Node ID, as a method to Session.

node: use method to access session's Node ID

---

radicle/src/git.rs
radicle/src/identity/project.rs
radicle/src/rad.rs
radicle/src/storage/git.rs
radicle/src/storage/refs.rs
radicle/src/test/arbitrary.rs

We move the identity branch out of `heads/` and to the old location:
refs/rad/id
We move the signed refs branch to:
refs/rad/sigrefs
Keeping both "special" branches under the same hierarchy makes things a bit easier to work with, and tells the user that they should be updated with special tooling.
We also revert to `rad/` because we no longer have the issue of having `rad/rad/id` when doing a checkout of the remote branch in a working copy.
Closes #22

Move `radicle/id` and `radicle/signature`

---

radicle-node/src/main.rs
radicle-node/src/service.rs
radicle-node/src/service/config.rs
radicle-node/src/test/peer.rs
radicle-node/src/tests.rs

Check to keep a healthy connection to the Radicle network when a disconnect occurs (up to 30 seconds), or when a node disconnects.
Also:
- Rename peer -> session
- Update recorded sessions when disconnect is official.
References #25

node: keep healthy connection to network

---

radicle-node/src/lib.rs

Fix a problem from a recent commit which caused tests in the tests module not to run.
The list of modules in 'lib.rs' should use the 'tests' module's new location.

node: make tests in tests mod run

---

Cargo.lock
radicle-cli/Cargo.toml
radicle-cli/src/commands.rs
radicle-cli/src/commands/ls.rs
radicle-cli/src/commands/patch.rs
radicle-cli/src/commands/patch/common.rs
radicle-cli/src/commands/patch/create.rs
radicle-cli/src/commands/patch/list.rs
radicle-cli/src/lib.rs
radicle-cli/src/terminal/format.rs
radicle-cli/src/terminal/patch.rs
radicle/src/cob.rs
radicle/src/cob/store.rs
radicle/src/rad.rs
radicle/src/storage.rs
radicle/src/storage/refs.rs

See commit. This is a port of the `radicle-cli` patch command.
The `sync` functionality is marked as `TODO` until we figure out what we want to do there. I didn't want to block this work from progressing because of that.
The other `TODO`s were there from the radicle-cli, so I kept them.

Implement `rad-patch` command

---

Cargo.lock
radicle-node/src/control.rs
radicle/Cargo.toml
radicle/src/node.rs

This was causing an issue in rust-analyzer, and probably would fail in other ways via cargo. In any case it wasn't a good idea.

Get around circular-dependency

---

radicle-node/src/service.rs

Send the node's configured external addresses instead of its listenning addresses.  External addresses are ones which the service is reachable from the outside world, the listening addresses can be the wrong context (local area network, or 0.0.0.0).
Signed-off-by: Slack Coder <slackcoder@server.ky>

node: Fix addresses sent to peers on conn.

---

radicle/src/identity/project/id.rs

Add `rad:` prefix to project ids

---

radicle-node/src/bounded.rs
radicle-node/src/lib.rs
radicle-node/src/main.rs
radicle-node/src/service.rs
radicle-node/src/service/config.rs
radicle-node/src/service/message.rs
radicle-node/src/test/arbitrary.rs
radicle-node/src/test/peer.rs
radicle-node/src/tests.rs
radicle-node/src/wire.rs
radicle-node/src/wire/message.rs

Support clearly defining message constraints by introducing a new vector type.  The vector type takes a statically defined upper bound as a Type parameter.
Should we pursue using this?  The code is to express the idea and not meant as a final version, some clean up will be in order.
```
pub struct InventoryAnnouncement {
/// Node inventory.
pub inventory: BoundedVec<INVENTORY_LIMIT, Id>,
/// Time of announcement.
pub timestamp: Timestamp,
}
```

node: try using static Vector limits

---

radicle-cli/examples/rad-init.md
radicle-cli/src/commands/checkout.rs
radicle-cli/src/commands/clone.rs
radicle-crypto/src/test/signer.rs
radicle-httpd/src/api/v1/delegates.rs
radicle/src/identity.rs
radicle/src/identity/project.rs
radicle/src/rad.rs
radicle/src/storage/git.rs
radicle/src/test/arbitrary.rs

We are working on other mechanisms to help identify keys, and this is just redundant.
Also update some of the CLI examples to create a canonical example for documentation.

Remove delegate names from identity doc

---

Cargo.lock
radicle-cob/Cargo.toml
radicle-cob/src/backend/git/change.rs
radicle-cob/src/history/entry.rs
radicle-cob/src/tests.rs
radicle-node/Cargo.toml
radicle/Cargo.toml
radicle/src/cob/issue.rs
radicle/src/cob/op.rs
radicle/src/cob/patch.rs
radicle/src/cob/store.rs
radicle/src/cob/thread.rs

Sometimes it is more efficient to perform multiple operations at once and store those in the collaborative object graph together.
Change the contents to be a non-empty sequence of byte sequences, i.e. NonEmpty<Vec<u8>>. These are stored as blobs in a git tree in order by their index in the non-empty sequence. They are, in turn, retrieved in order of their original index.
Change the conversion of an `EntryWithClock` to return a non-empty sequence of `Op`s, which are in turn used to apply many changes in each `from_history` implementation.

cobs: allow for batched operations

---

radicle-cli/src/commands/clone.rs
radicle-cli/src/commands/track.rs
radicle-cli/src/commands/untrack.rs
radicle-node/src/client/handle.rs
radicle-node/src/control.rs
radicle-node/src/service.rs
radicle-node/src/test/handle.rs
radicle-node/src/tests.rs
radicle-remote-helper/src/lib.rs
radicle-tools/src/rad-clone.rs
radicle-tools/src/rad-push.rs
radicle/src/node.rs
radicle/src/rad.rs

I'm not super happy with the proliferation of `track_repo`, `track_node` etc., but I think it's ok for now. I'd like to refactor at some point once it's clearer what we need, and once we find a nice abstraction for it.

Tracking of peers via the CLI, and aliases

---

radicle-node/src/bounded.rs
radicle-node/src/service.rs
radicle-node/src/service/message.rs
radicle-node/src/test/arbitrary.rs
radicle-node/src/test/peer.rs
radicle-node/src/wire.rs
radicle-node/src/wire/message.rs
radicle/src/test/arbitrary.rs

Use the BoundedVec to limit the supported number of refs in RefAnnouncement messages.  The size (236) is the maximum supported by message wire size.
To reduce the complexity of the changes, BoundedVec is used again instead of using a new bounded Refs or BTreeMap.  This requires defining new Decode/Encode logic for Ref's element types, and workarounds for arbitrary instances.
Signed-off-by: Slack Coder <slackcoder@server.ky>
closes #16

node: Limit number of Refs in RefAnnouncements

---

radicle-cli/src/commands/inspect.rs
radicle/src/identity.rs
radicle/src/identity/doc.rs
radicle/src/rad.rs
radicle/src/storage/git.rs

In RIP-2, we specify that identity document root commits must include the signature of all founding delegates.
This commit adds the required signatures during document creation and verifies them on load.

Verify identity root commit signatures

---

.nix/sources.json

To match the new toolchain update, run `niv update` to get the latest rust-1.66.

nix: update sources for rust-1.66

---

radicle-cli/examples/rad-issue.md
radicle-cli/src/commands.rs
radicle-cli/src/commands/assign.rs
radicle-cli/src/commands/issue.rs
radicle-cli/src/commands/unassign.rs
radicle-cli/src/main.rs
radicle-cli/src/terminal/table.rs
radicle-cli/tests/commands.rs
radicle-cob/src/backend/git.rs
radicle-cob/src/backend/git/change.rs
radicle/src/cob/issue.rs

Introduce two changes:
- Support command tool example tests by improving idempotence (https://github.com/radicle-dev/heartwood/pull/159/commits/9c5c0e89fdecb7a7c2ae98d039c7ddca67564f18)
- Add assign/unassign subcommands (https://github.com/radicle-dev/heartwood/pull/159/commits/458fcaeff676c3faa61e181b1cecca8ff06e4c19)
Issue #148

Assign issues using rad command + improve client example tests

---

radicle-httpd/src/api.rs
radicle-httpd/src/lib.rs

This allows prefix of each route e.g. `/api/*` to be visible in logs.
What we're getting before this PR:
```
2022-12-26T09:19:28.136224Z  INFO request{method=GET uri=/ status=200 latency=690.625µs}: radicle_httpd::api: Processed
2022-12-26T09:19:28.137226Z  INFO request{method=GET uri=/v1/node status=200 latency=280.434µs}: radicle_httpd::api: Processed
```
What we'd get with this PR:
```
2022-12-26T11:52:53.029381Z  INFO request{method=GET uri=/api status=200 latency=475.951µs}: radicle_httpd: Processed
2022-12-26T11:52:53.029564Z  INFO request{method=GET uri=/api/v1/node status=200 latency=261.168µs}: radicle_httpd: Processed
^
```

httpd: Use `TraceLayer` on uppermost router

---

radicle-cli/examples/rad-delegate.md
radicle-cli/src/commands.rs
radicle-cli/src/commands/checkout.rs
radicle-cli/src/commands/clone.rs
radicle-cli/src/commands/delegate.rs
radicle-cli/src/commands/delegate/add.rs
radicle-cli/src/commands/delegate/list.rs
radicle-cli/src/commands/delegate/remove.rs
radicle-cli/src/commands/init.rs
radicle-cli/src/commands/ls.rs
radicle-cli/src/commands/patch/create.rs
radicle-cli/src/commands/track.rs
radicle-cli/src/commands/untrack.rs
radicle-cli/src/main.rs
radicle-cli/tests/commands.rs
radicle/src/identity.rs
radicle/src/identity/did.rs
radicle/src/identity/doc.rs
radicle/src/identity/project.rs
radicle/src/rad.rs
radicle/src/storage/git.rs
radicle/src/test/arbitrary.rs

This series allows the adding, removing, and listing of delegates.
It's limited to projects that have a threshold of 1 since we need to be able to gather signatures for an identity that needs a higher threshold.
The update of an identity with a higher threshold will be tackled in a separate series.

Manage project delegates iff threshold = 1

---

radicle-cli/tests/commands.rs
radicle-cli/tests/framework/mod.rs

We were setting the CWD for the parent process, which wasn't such a good idea.
Signed-off-by: Alexis Sellier <self@cloudhead.io>

cli: Fix flaky tests

---

Cargo.lock
Cargo.toml
radicle-cob/Cargo.toml
radicle-cob/src/change_graph.rs
radicle-cob/src/change_graph/evaluation.rs
radicle-cob/src/history.rs
radicle-cob/src/object/collaboration/info.rs
radicle-crypto/src/ssh/keystore.rs
radicle-dag/Cargo.toml
radicle-dag/src/lib.rs

Switch to our own DAG representation for COBs
We're using petgraph to encode an operation based CRDT (each graph node
is an operation) as a DAG, and one of the important things to ensure
is that the final state is not influenced by the order of concurrent
operations. In this case a concurrent operation would mean two potential
graph traversal orders, as there's no direct edge between the two
concurrent ops. This is essential a "partial order" of operations.
To be able to test this, we'd want some kind of control over how
neighbors are iterated over I guess, when there's more than one possible
sort order. Say we have a graph like this:
```
┌────────b◄─────┐
▼               │
a               d
▲               │
└────────c◄─────┘
```
There are two possible topological traverse orders: [a, b, …

Allow for arbitrary COB history graph-traversal orders

---

.github/workflows/release.yml

So far this job successfully produces (see https://github.com/radicle-dev/heartwood/actions/runs/3750372267):
```
radicle-cli-aarch64-apple-darwin.tar.gz
radicle-cli-aarch64-unknown-linux-musl.tar.gz
radicle-cli-x86_64-apple-darwin.tar.gz
radicle-cli-x86_64-unknown-linux-musl.tar.gz
radicle-cli_amd64.deb
```
To do before merging:

CI job to publish CLI binaries

---

.github/workflows/actions.yml
.github/workflows/frontend-testing.yml

On a push to master, this job is going to upload `radicle-httpd` binary to a Google Cloud Storage bucket at a path `gs://heartwood-artifacts/<THIS_REPO_COMMIT_SHA>/radicle-httpd` that can subsequently be used in e2e tests [[1]] by simply downloading and executing it (since it’s statically linked).  e2e tests will check if `radicle-httpd` at the given `COMMIT_SHA` pass playwright tests.
[1]: https://github.com/radicle-dev/radicle-interface/blob/master/.github/workflows/check-e2e.yml

Publish radicle-httpd binary for testing

---

radicle-cli/src/commands/inspect.rs

Remove redundant 'collect()' call.
Signed-off-by: Slack Coder <slackcoder@server.ky>

cli: simplify inspect

---

.github/workflows/actions.yml
radicle-cli/examples/rad-patch.md
radicle-cli/src/commands/patch.rs
radicle-cli/src/commands/patch/create.rs
radicle-cli/src/commands/patch/list.rs
radicle-cli/tests/commands.rs

Make `rad patch` accept subcommands for specifying its operation in place of the '--command' notation.
For instance `rad patch update` versus `rad patch --update`.  Also make the default operation list active patches, replacing patch creation. Patch creation is now done via `rad patch open`.
Make these changes in a way consistent with other commands like `rad delegate`.
Add '--no-confirm' to patch to support this subcommand's documentation test.
References: #148

cli: alter use subcommands for patch

---

radicle-node/src/service.rs
radicle-node/src/test/peer.rs
radicle-node/src/tests/e2e.rs
radicle-node/src/wire/protocol.rs

This change makes sure that nodes don't gossip announcements back to the announcers.
Since the tests were relying on this mechanism to populate the routing table, we had to change a few more things, such as adding the inventory to the node's routing table.
Signed-off-by: Alexis Sellier <self@cloudhead.io>

node: Fix redundant announcements

---

radicle-cli/src/commands/issue.rs

This is poor UX imo and I'd prefer it if we show the emojis in terminal somehow (like a TUI). Still the flag needs to be renamed to match the `help`.

rad-issue: Change `reaction` flag to `emoji`

---

.github/workflows/ci.yaml

Resolves warnings from GitHub Actions like “The `set-output` command is deprecated and will be disabled soon”.

Switch to maintained GitHub actions for Rust

---

Cargo.lock
radicle-cli/Cargo.toml
radicle-cli/src/commands.rs
radicle-cli/src/commands/web.rs
radicle-cli/src/main.rs
radicle-httpd/Cargo.toml
radicle-httpd/src/api.rs
radicle-httpd/src/api/auth.rs
radicle-httpd/src/api/error.rs
radicle-httpd/src/api/test.rs
radicle-httpd/src/api/v1/delegates.rs
radicle-httpd/src/api/v1/projects.rs
radicle-httpd/src/api/v1/sessions.rs
radicle-httpd/src/api/v1/stats.rs

- adding `rad web` to the CLI to allow users to authenticate their browsers with a running `radicle-httpd` instance.
- rewriting `radicle-httpd` to authenticate users with their Radicle identity instead of SIWE.
- We can probably return to SIWE at some point, but for the goal to write and edit issues and comments is more achievable with the local identity.

Add new command to CLI and endpoints to authenticate UI with httpd through CLI

---

Cargo.lock
radicle-crdt/Cargo.toml
radicle-crdt/src/clock.rs
radicle/src/cob/op.rs

To help users, create an Op ID string format of the form '[cob::op::ActorId]/[cob::op::Lamport]'.
The formatting is not final and is intended to support development around interfacing with comments.
References: #245

Add Op ID string formatting

---

radicle-httpd/Cargo.toml
radicle-httpd/src/api.rs
radicle-httpd/src/api/auth.rs
radicle-httpd/src/api/json.rs
radicle-httpd/src/api/v1/sessions.rs

We currently don't have a way on for the web app to check the validity of a session_id, so we need a route to do that.
Also I didn't want to limit OK responses just to authorized sessions, but also return a OK response with the Unauthorized session information, which can become handy.

radicle-httpd: Add `GET /api/v1/sessions/:id` route to get session information

---

radicle-node/src/main.rs

Define the help message in an obvious location and describe some of the arguments.

node: Elaborate --help message

---

radicle-cli/examples/rad-patch.md
radicle-cli/src/commands/comment.rs
radicle-cli/src/commands/patch.rs
radicle-cli/src/commands/patch/common.rs
radicle-cli/src/commands/patch/create.rs
radicle-cli/src/commands/patch/update.rs
radicle-cli/src/commands/review.rs
radicle-cli/src/terminal/patch.rs

Simplify codebase by splitting patch::create::run() into patch::create::run() and
patch::update::run().
Patch has the subcommands `create` and `update` but both use the same
method to do the heavy lifting.  Spitting the code allows us to detangle
the code path making it easier to follow.
Also, reduce cognitive load by minimizing the amount of variables used
and isolating them to utility functions.  For instance, `head_branch` can be passed to
these methods instead of `head_oid` and `head_branch`.

`rad patch` refactor

---

radicle-cli/examples/rad-patch.md
radicle-cli/src/commands/comment.rs
radicle/src/cob/patch.rs

Allow commenting on a patch as well an issue.
References: #187

cli: Support patch commenting

---

radicle-cli/src/commands/web.rs

Since sessionStorage and localStorage use protocol + host + port as scope, we want to align this between the CLI and radicle-interface. Using localhost has other benefits as well, because browsers treat it differently when doing requests from the deployed app which is being served via https.

cli: Use localhost for rad web

---

radicle-cli/examples/rad-issue.md
radicle-cli/examples/rad-patch.md
radicle-cli/src/commands/comment.rs

Allow replying to patch and issue comments using `rad comment --reply-to` option.
references #187

rad:  Add comment `reply-to`

---

radicle-httpd/src/api.rs

I forgot to add DELETE to the allowed methods of the httpd in the PR #273

radicle-httpd: Add DELETE to allowed methods

---

radicle-cli/examples/rad-issue.md
radicle-cli/tests/commands.rs
radicle-httpd/src/api/auth.rs
radicle-httpd/src/api/json.rs
radicle-httpd/src/api/test.rs
radicle-httpd/src/api/v1/projects.rs
radicle-httpd/src/api/v1/sessions.rs
radicle/src/cob/thread.rs

- Adds a `PATCH` method to `api::test` for e.g. updating issues.
- Adds endpoint tests for creating issues, creating a top-level comment, and replying to a comment.
- Also moves around some parts for better DX

radicle-httpd: Add more issue endpoint tests

---

radicle-cob/src/trailers.rs

The macro in the trailers module existed since there were multiple trailers before the refactoring, so it minimised boilerplate code.
After the refactoring of the code there was only one trailer left. Remove the macro generation code and replace it with just the necessary code for the ResourceCommitTrailer.

radicle-cob: simplify trailers module

---

radicle/src/identity/doc.rs
radicle/src/storage/git.rs

Fixes #291 
The signatures for Radicle identities were using the documents content.
It is standard to use the hash of the content instead, since signing and verification is faster on a smaller set of data.
Use the resulting Git blob's object id, i.e. `git hash-object`, as the signing and verifying payload.

radicle: sign blob hash instead of content

---

radicle-cli/examples/rad-issue.md
radicle-cli/src/commands/issue.rs
radicle-httpd/src/api/test.rs
radicle-httpd/src/api/v1/projects.rs
radicle/src/cob/issue.rs

We currently don't allow to pass assignees during the issue creation.
This PR allows the passing of a vector of ActorIds during issue creation by the httpd or the cli
Also modifies some tests to check that the issue creation, handles tags and assignees accordingly

radicle-httpd: Add `assignees` to Issues::create

---

Cargo.lock
radicle-httpd/Cargo.toml
radicle-httpd/src/api.rs
radicle-httpd/src/api/error.rs
radicle-httpd/src/api/v1/delegates.rs
radicle-httpd/src/api/v1/projects.rs

This PR adds the delegates available to a remote to the project route.
```diff
http://0.0.0.0:8080/api/v1/projects/rad:z2wBFUvWarjNbKBuDJ7CBTxeg8dqg
{
"name": "issue-test-repo",
"description": "TBD",
"defaultBranch": "master",
+   "delegates": [
+     "did:key:z6Mkv3pqBci7JY2uChMWhtVhVKcNfr84ZidpZekdRF6MkF3E"
+   ],
"head": "daafeb8ac3650b98fd12492bac0f7d5ef64f8c80",
"patches": 0,
"issues": 5,
"id": "rad:z2wBFUvWarjNbKBuDJ7CBTxeg8dqg"
}
```
```diff
http://0.0.0.0:8080/api/v1/projects
[
{
"name": "issue-test-repo",
"description": "TBD",
"defaultBranch": "master",
+     "delegates": [
+       "did:key:z6Mkv3pqBci7JY2uChMWhtVhVKcNfr84ZidpZekdRF6MkF3E"
+     ],
"head": "daafeb8ac3650b98fd12492bac0f7d5ef64f8c80",
"patches": 0,
"issues": 5,
"id": "rad:z2wBFUvWarjNbKBuDJ7CBTxeg8dqg"
}
]
```

radicle-httpd: Add delegates to project routes

---

Cargo.lock
Cargo.toml
radicle-cli-test/Cargo.toml
radicle-cli-test/src/lib.rs
radicle-cli/Cargo.toml
radicle-cli/tests/commands.rs

To allow that functionality to be published for reuse.
Signed-off-by: xla <self@xla.is>

cli: Extract crate for md based tests

---

radicle-cli/src/commands/patch.rs

The `list` and `show` commands were missing from the HELP message.
Add them to the HELP message.

cli: add missing patch commands

---

radicle-cli/examples/rad-patch.md
radicle-cli/src/commands/patch.rs
radicle-cli/src/commands/patch/checkout.rs

This implements the `patch checkout <patch id>` command and updates the tests
I was thinking to add an cli flag to customize the branch name, but I guess this could be done later

Add possibility to checkout a patch 

---

radicle-node/src/main.rs

Document the `--git-daemon` argument and describe the default values for is and the listening address.

node: Add more command argument documentation

---

Cargo.lock
radicle-cob/Cargo.toml
radicle-crypto/Cargo.toml
radicle-crypto/src/lib.rs
radicle-crypto/src/ssh/keystore.rs
radicle-crypto/src/test/signer.rs
radicle-node/Cargo.toml
radicle-node/src/runtime.rs
radicle-node/src/runtime/handle.rs
radicle-node/src/service.rs
radicle-node/src/service/message.rs
radicle-node/src/test/environment.rs
radicle-node/src/test/peer.rs
radicle-node/src/wire/message.rs
radicle-node/src/wire/protocol.rs
radicle-node/src/worker.rs
radicle/Cargo.toml

Move from NoiseNN with a custom authentication protocol, to NoiseXK.
Uses ECDH on the ed25519 curve via the `ec25519` library.

node: Move to NoiseXK

---

radicle-node/src/service.rs
radicle-node/src/service/message.rs
radicle-node/src/service/session.rs
radicle-node/src/test/environment.rs
radicle-node/src/test/peer.rs
radicle-node/src/tests.rs
radicle-node/src/wire/message.rs

With `NoiseXK` handshake implemented, there is no longer a need to have an `Initialize` message and an extra state in the session.

node: Remove redundant handshake

---

radicle-node/src/test/environment.rs
radicle/src/profile.rs
radicle/src/test.rs

If a path was passed to `Home` in non-canonical form it would not use the right path for any initialisation or use.
The aim is to use the `canonicalize` function for paths. However, this may return an error if none of the paths exist. To ensure that the path exists the `new` constructor for `Home` creates the directory and canonicalizes the path.
Since `new` now initialises the home directory, it would be useful if it also initialised all the necessary subdirectories -- which removes the need for the `init` method.
Fixes #313

radicle: canonicalize home path

---

radicle-cli/examples/rad-auth.md
radicle-cli/examples/rad-delegate.md
radicle-cli/examples/rad-id-rebase.md
radicle-cli/examples/rad-id.md
radicle-cli/examples/rad-issue.md
radicle-cli/src/commands/assign.rs
radicle-cli/src/commands/auth.rs
radicle-cli/src/commands/checkout.rs
radicle-cli/src/commands/delegate.rs
radicle-cli/src/commands/edit.rs
radicle-cli/src/commands/id.rs
radicle-cli/src/commands/issue.rs
radicle-cli/src/commands/rm.rs
radicle-cli/src/commands/self.rs
radicle-cli/src/commands/unassign.rs
radicle-cli/src/terminal/args.rs
radicle/src/cob/issue.rs
radicle/src/identity/did.rs
radicle/src/profile.rs

The aim of this proposal is to standardise the use of `Did` over `PublicKey`, `ActorId`, or `NodeId` when accepting arguments in the CLI as well as printing out the identifier during CLI execution.
In a couple of spots, I opted to keep the `NodeId` being printed out but also print out the `Did`.
Fixes #324

Use `Did` across CLI tooling

---

Cargo.lock
radicle-cli/examples/rad-id-rebase.md
radicle-cli/examples/rad-id.md
radicle-cli/src/commands/patch/common.rs
radicle-cli/src/commands/patch/list.rs
radicle-httpd/Cargo.toml
radicle-httpd/src/api/json.rs
radicle-httpd/src/api/v1/projects.rs
radicle/src/cob/common.rs
radicle/src/cob/identity.rs
radicle/src/cob/issue.rs
radicle/src/cob/patch.rs
radicle/src/identity/did.rs

Instead of showing just public keys we need to show the fully qualified spec for a NID which is prefixed by `did:key:` While we want to maintain `Author` and `ActorId` for internal use.

Use `Did` for json output and other places

---

radicle-httpd/src/api/test.rs
radicle/src/profile.rs

The `From` implementation would allow someone to create a `Home` in an incorrect fashion, for example the path is not canonical.
Exchange `From` for a `TryFrom` implementation.

radicle: exchange From for TryFrom for PathBuf and Home

---

radicle-cli/src/commands/help.rs

The assign, id, and unassign help messages were missing from the rad help command.
Add them to complete the list.

cli: add missing commands for rad_help

---

Cargo.lock
radicle/Cargo.toml
radicle/src/canonical.rs
radicle/src/canonical/formatter.rs
radicle/src/cob/issue.rs
radicle/src/cob/store.rs
radicle/src/identity/doc.rs
radicle/src/lib.rs

The olpc-json crate's CanonicalFormatter does not escape certain control characters, including new lines. This means that when a COB gets serialized that includes new lines, those new lines are serialized verbatim. Upon deserialization `serde_json` -- and any other JSON deserializer -- will fail due to the encounter of these control characters.
This behaviour was prevented in radicle-link with the definition of its own CanoncialFormatter that encodes the control characters correctly.
Inline this definition of the formatter, under MIT license, to ensure the correct and remove oplc-cjson.
The behaviour is checked using a multiline test in the issue COB.
Fixes #351

radicle: custom CanonicalFormatter

---

radicle-httpd/src/api.rs
radicle-httpd/src/api/v1/delegates.rs
radicle-httpd/src/api/v1/projects.rs
radicle/src/cob/issue.rs
radicle/src/cob/patch.rs

To allow the web client to show the amounts of issues and patches in their different states without fetching them all, I propose that this should be done by the radicle-httpd.
There is probably a more optimized way of doing this, feel free to suggest optimizations!
The idea is to have a JSON output like the following:
```diff
[
{
"name": "test-heartwood",
"description": "test-description",
"defaultBranch": "master",
"delegates": [
"did:key:z6MkkfM3tPXNPrPevKr3uSiQtHPuwnNhu2yUVjgd2jXVsVz5"
],
"head": "1dc55cc08ab5f72c1ad552effb115665bde03990",
"patches": {
+     "proposed": 0,
+     "draft": 0,
+     "archived": 0
},
"issues": {
+    "open": 11,
+    "closed": 0
},
"id": "rad:z22nAstJ662ouwRwADTpuzB6R9hVq"
}
]
```

radicle-httpd: Group issue and patch states in project endpoint

---

radicle-node/src/control.rs
radicle-node/src/runtime/handle.rs
radicle-node/src/test/handle.rs
radicle/src/node.rs

The Handle trait defines a FetchResult associated type. This type is always instantiated to be the FetchResult enum in radicle::node.
Remove the associated type to simplify the trait.

radicle: remove FetchResult associated type

---

radicle-cli/src/commands/clone.rs
radicle-node/src/runtime/handle.rs
radicle-node/src/service.rs
radicle-node/src/service/session.rs
radicle-node/src/test/handle.rs
radicle-node/src/tests/e2e.rs
radicle/src/node.rs

Previously, the seeds information would only consist of the connected NodeIds.
Improve on this by adding any disconnected and fetching seeds as well. A seed can either be disconnected, connected, or fetching -- where fetching implies connected.
To be able to see which NodeIds are being fetched from, it's necessary to add this information to the Session.
Fixes #343

node: improve seeds information

---

radicle-httpd/src/api.rs
radicle-httpd/src/api/error.rs
radicle-httpd/src/api/v1/delegates.rs
radicle-httpd/src/api/v1/projects.rs

related https://github.com/radicle-dev/heartwood/issues/295

httpd: Use `repo.identity_doc()` instead of `repo.identity_of(..)`

---

radicle-httpd/src/api/v1/projects.rs
radicle/src/cob/issue.rs

As talked on zulip https://radicle.zulipchat.com/#narrow/stream/369277-heartwood/topic/cobs.20pagination
We need the issues and patches to be returned from `GET /projects/:project/issues` and `GET /projects/:project/patches` to be sorted before doing the pagination.
This will allow us to receive the same output every time we call the endpoint with the same params.

radicle-httpd: sort cobs listing endpoints

---

radicle-cli/src/main.rs

Make `rad fetch` accessible via the command line.  It appears to be accidently left out.

cli: expose `rad fetch`

---

radicle-httpd/Cargo.toml
radicle-httpd/src/lib.rs
radicle-httpd/src/main.rs
radicle-httpd/src/tracing_extra.rs

```bash
2023-03-02T14:37:01.282222Z  INFO radicle_httpd: version 0.1.0-1bb6f9a
2023-03-02T14:37:01.282780Z  INFO radicle_httpd: git version 2.34.1
2023-03-02T14:37:01.282943Z  INFO radicle_httpd: using radicle home at /tmp/rad_test
2023-03-02T14:37:01.283585Z  INFO radicle_httpd: listening on http://0.0.0.0:8080
2023-03-02T14:37:02.909666Z ERROR request{id=0}: radicle_httpd::error: invalid radicle identifier: Unknown base code: a
2023-03-02T14:37:02.909745Z  INFO request{id=0}: radicle_httpd: 127.0.0.1:35938 "GET /ax/xa HTTP/1.1" 404 Not Found 213.241µs 0
2023-03-02T14:37:03.816727Z  INFO request{id=1}: radicle_httpd: 127.0.0.1:35954 "GET /api/v1/projects/jk HTTP/1.1" 400 Bad Request 358.013µs 48
2023-03-02T14:37:05.393990Z  INFO request{id=2}: radicle_httpd: 127.0.0.1:35970 "GET …
```

httpd: Change format of tracing messages

---

radicle-httpd/src/api/error.rs
radicle-httpd/src/api/v1/projects.rs
radicle-httpd/src/test.rs

This PR adds a new endpoint to create new patches through the httpd that can be called as follows:
```
curl -H 'Content-Type: application/json' \
-d '{ "title":<title>,"description":<description>, "target":<target_oid>, "oid":<head_oid>, "tags":[] }' \
-X POST \
-H "Authorization: Bearer <session_id>" \
http://0.0.0.0:8080/api/v1/projects/:project/patches
```

radicle-httpd: Add patch creation endpoint

---

radicle-httpd/src/test.rs

Once https://github.com/radicle-dev/heartwood/pull/393 merges, we can entirely remove `radicle_cli` from dependencies of `httpd`.

httpd: Remove `radicle_cli` from tests

---

radicle-node/src/service.rs
radicle-node/src/service/reactor.rs
radicle-node/src/test/simulator.rs
radicle-node/src/tests.rs
radicle-node/src/wire/protocol.rs
radicle-node/src/worker.rs

A fetch is a client-server interaction and so there are two sides to this interaction. These sides are generally referred to as receive -- the client side -- and upload -- the server side.
The `Fetch` type indicated whether it was doing a receive or upload by using a field `initiated: bool`. However, this can be confusing when you pair it with the `namespaces: Namespaces` field, since only the receive side should be sending what refspecs it wants and the upload side responds with those matching refspecs.
A better way to represent this is using an enum for which direction the fetch is being considered, where the receive side contains the Namespaces.
The resulting code then makes decisions based on what variant of the enum was passed.
Fixes #379

node: use enum for fetch direction

---

radicle-cli/src/commands/issue.rs

Fix the command line silents abort when the
the `EDITOR` variable is not specified.
With this commit the result is reported below
```
➜  rio git:(main) RAD_PASSPHRASE=12345 rad issue open
✗ Issue failed: editor not configured: the `EDITOR` environment variable is not set
```

fix: fix command line silent abort

---

radicle-cli/examples/rad-node.md
radicle-cli/src/commands/clone.rs
radicle-cli/src/commands/init.rs
radicle-cli/src/commands/node/tracking.rs
radicle-cli/tests/commands.rs
radicle-node/src/control.rs
radicle-node/src/runtime.rs
radicle-node/src/runtime/handle.rs
radicle-node/src/service.rs
radicle-node/src/service/config.rs
radicle-node/src/service/session.rs
radicle-node/src/service/tracking.rs
radicle-node/src/service/tracking/store.rs
radicle-node/src/test/environment.rs
radicle-node/src/test/handle.rs
radicle-node/src/test/peer.rs
radicle-node/src/test/simulator.rs
radicle-node/src/tests.rs
radicle-node/src/tests/e2e.rs
radicle-node/src/worker.rs
radicle/src/identity/doc.rs
radicle/src/node.rs
radicle/src/node/tracking.rs
radicle/src/storage.rs
radicle/src/test/arbitrary.rs
radicle/src/test/storage.rs

The fetch implementation will potentially fetch the local operator's remote, which is unnecessary and could result in deleted data.
Fix this by threading the local operator's public key and add an ignore refspec to the fetch arguments, i.e.
^refs/namespaces/<local>/*
The implementation also strictly fetches all or one namespace. This is improved upon by introducing a new variant for specifying a set of namespaces.
Fixes #317

node: improve fetch

---

radicle-cli/examples/rad-node.md
radicle-cli/examples/rad-track.md
radicle-cli/src/commands/track.rs
radicle-cli/tests/commands.rs

Allows the `track` command to be used to track nodes and repos.
Closes #312

cli: Update `track` command

---

radicle-node/src/service.rs
radicle-node/src/service/session.rs

It's possible for a peer to disconnect before responding with `FetchOk`. In that case, we make sure to return to any pending fetch request with an error. Closes #382

node: Handle `FetchOk` never being received

---

Cargo.lock
radicle-cli/examples/rad-id-rebase.md
radicle-cli/examples/rad-id.md
radicle-cli/examples/rad-issue.md
radicle-cli/examples/rad-patch.md
radicle-cob/src/backend/git/change.rs
radicle-cob/src/change_graph/evaluation.rs
radicle-cob/src/history.rs
radicle-cob/src/history/entry.rs
radicle-cob/src/lib.rs
radicle-cob/src/object.rs
radicle-cob/src/object/collaboration.rs
radicle-cob/src/object/collaboration/update.rs
radicle-cob/src/tests.rs
radicle-httpd/src/api/error.rs
radicle-httpd/src/api/json.rs
radicle-httpd/src/api/v1/projects.rs
radicle-httpd/src/test.rs
radicle/Cargo.toml
radicle/src/cob.rs
radicle/src/cob/identity.rs
radicle/src/cob/issue.rs
radicle/src/cob/op.rs
radicle/src/cob/patch.rs
radicle/src/cob/store.rs
radicle/src/cob/test.rs
radicle/src/cob/thread.rs

By introducing a small limitation: only allowing entries in the change graph to be addressable, instead of individual operations; we drastically simplify the CRDT implementation.
There are four advantages:
1. Op ids are just regular SHA-1s
2. There's no need for relative IDs, ops never refer to other ops within the same commit
3. There's no need for a nonce, since commits can't collide, and neither can op IDs
4. `OpId` can just be an alias of `EntryId`
The disadvantage of course, is that we have to be mindful of how we create op transactions, since each transaction creates an addressable unit. For example, we must not include multiple patch revisions in the same transaction.
**TODO**

cob: Use `EntryId` as the operation identifier

---

radicle-cli/examples/rad-patch.md
radicle-cli/src/commands/patch/common.rs
radicle-cli/src/commands/patch/create.rs
radicle-cli/src/commands/patch/update.rs

Correct assumptions made about how patching work in `rad patch`.  Make the default Patch target a `git ref` in place of a target 'peer'.
Use the canonical head as the git reference.  This is head of the project's master branch which project delegates have concensus on.
The process is simplified by ignoring the case of other delegates having merged the changes.  This would be an rare circumstance which can be handled by the maintainers/contributor for the rare circumstance it happens in.

cli: use canonical head for patch target

---

radicle-httpd/src/error.rs
radicle-httpd/src/git.rs
radicle-httpd/src/lib.rs
radicle-httpd/src/main.rs
radicle-httpd/src/test.rs

Allows cloning via git using an alias instead of the full RID.
Eg. `git clone https://seed.radicle.xyz/heartwood.git`

httpd: Basic alias support for git

---

radicle-httpd/src/api.rs
radicle-httpd/src/api/v1.rs

```console
$ curl localhost:8080/api | jq
{
"path": "/api",
"links": [
"/v1"
]
}
$ curl localhost:8080/api/v1 | jq
{
"message": "Welcome!",
"service": "radicle-httpd",
"version": "0.1.0-b2c2b65",
"node": {
"id": "z6MkqgfPWLDruEjqzY5enrrqSSSxpARdFsQK6DWJfBBV9AV4"
},
"path": "/api/v1",
"links": [
{
"href": "/projects",
"rel": "projects",
"type": "GET"
},
{
"href": "/node",
"rel": "node",
"type": "GET"
},
{
"href": "/delegates/:did/projects",
"rel": "projects",
"type": "GET"
},
{
"href": "/stats",
"rel": "stats",
"type": "GET"
}
]
}
```

httpd: Serve root handler on `/api/v1` instead of `/api`

---

radicle-cli/examples/rad-issue.md
radicle-cli/src/commands/issue.rs

After an issue is opened there is no feedback from the command line
that the issue is created correctly, so this is calling `show_issue` to 
print the issue result on the command line.
Also, I'm proposing a new show issue format on the terminal
because the previous one looks a little bit odd to me in
comparison with the other rad commands.

[RFC] show the issue when it is created 

---

radicle-cli-test/src/lib.rs
radicle-cli/tests/commands.rs
radicle-node/src/service.rs
radicle-node/src/tests.rs
radicle/src/storage/git.rs

Periodically, make sure we try to fetch inventory that is tracked
but missing from local storage.
We decide not to fetch immediately on `TrackRepo`, as this limits
the command's flexibility. For example, when `rad clone` is used,
we want to be able to fetch manually after tracking.
Closes #364

node: Fetch missing inventory 

---

radicle-cli/src/commands/node/tracking.rs
radicle-node/src/control.rs
radicle-node/src/runtime/handle.rs
radicle-node/src/service.rs
radicle-node/src/test/handle.rs
radicle/src/node.rs

I was finding the current naming misleading, as the returned entries could be for blocked repos/nodes.

node: Rename `tracked_repo` -> `repo_policies`

---

radicle-cli/examples/rad-tag.md
radicle-cli/src/commands.rs
radicle-cli/src/commands/help.rs
radicle-cli/src/commands/tag.rs
radicle-cli/src/commands/untag.rs
radicle-cli/src/main.rs
radicle-cli/tests/commands.rs

These commands are added at the top level because they will eventually also work on patches.
We can also eventually implement an alias `rad issue tag` that just calls `rad tag` but forces the argument to be an issue.
Closes #344

cli: Implement `tag` and `untag`

---

CONTRIBUTING.md

Add code guidelines and instructions.

Flesh out `CONTRIBUTING.md`

---

radicle-httpd/src/api/v1/projects.rs

It seems like this was set to 302 by mistake. We're not setting any location headers, so when querying this endpoint with with `fetch` from a JS frontend and then do `.json()` on the result, it throws an error.
```
{
error: TypeError: terminated
...
[cause]: DOMException [AbortError]: The operation was aborted.
...
}
}
```

httpd: Fix status code in commit history endpoint

---

radicle-node/src/service.rs
radicle-node/src/service/session.rs
radicle-node/src/service/tracking.rs
radicle/src/storage.rs
radicle/src/test/storage.rs

It's not a good idea to have fallible operations run after `FetchOk`
is received, since there's no easy way to communicate the error
to the remote at that point. Hence, we compute namespaces earlier
in the process, and store the namespaces in the session.

node: Fail fast when repository can't be read

---

radicle-node/src/deserializer.rs
radicle-node/src/service.rs
radicle-node/src/test/peer.rs
radicle-node/src/tests.rs
radicle-node/src/wire/message.rs
radicle-node/src/wire/protocol.rs
radicle-node/src/worker.rs

It's possible that the daemon or stream closes the git connection without reading the final `done` packet. If this is the case, we try to read it after either of the connections is closed.
This may potentially mitigate the issue where the node then receives the `done` packet while in gossip mode, and disconnects the remote for misbehavior.

node: Fix potential protocol mismatch on fetch

---

radicle-node/src/service/tracking.rs

We were using the default scope instead of the entry scope.

node: Use correct scope when getting namespaces

---

radicle-httpd/src/api/json.rs
radicle-httpd/src/api/v1/projects.rs

Allows the web client to show timestamps for when a patch had its first revision, and to allow timestamps for the following revisions to show.

radicle-httpd: Add timestamp to revisions api::json

---

radicle-node/src/service.rs
radicle-node/src/service/message.rs
radicle-node/src/tests.rs

This change ensures that on `Subscribe`, we only relay the latest announcement of each node, per announcement category.
Previously, we would relay all announcement, while only the last one was relevant.

node: Don't relay redundant gossip messages

---

radicle-httpd/src/api.rs
radicle-httpd/src/api/v1/projects.rs

It's more ergonomic to consume in JS/TS. 🤷

Use camelCase in query params

---

.github/workflows/ci.yaml
radicle-cli/examples/workflow/1-new-project.md
radicle-cli/examples/workflow/2-cloning.md
radicle-cli/examples/workflow/3-issues.md
radicle-cli/examples/workflow/4-patching-contributor.md
radicle-cli/examples/workflow/5-patching-maintainer.md
radicle-cli/tests/commands.rs

Aid new users by documenting radicle usage via a workflow.  Order the examples to help user navigation and remove redundant example tests already covered by the workflow.

Document radicle workflow

---

radicle-httpd/src/api/json.rs
radicle-httpd/src/api/v1/projects.rs
radicle/src/cob/patch.rs

For display purposes in the web client, we add with this commit the some needed properties to the revisions in the patch endpoint.

radicle-httpd: Add more revision properties to patch endpoint

---

radicle/src/profile.rs

On MacOS the following error appears when running the test suite
```
thread 'profile::test::canonicalize_home' panicked at 'assertion failed: `(left == right)`
left: `"/private/var/folders/r9/dcp4ksl90dnfj2kqg7g7nbd40000gn/T/.tmpuewkuK/Home/Radicle"`,
right: `"/var/folders/r9/dcp4ksl90dnfj2kqg7g7nbd40000gn/T/.tmpuewkuK/Home/Radicle"`', radicle/src/profile.rs:253:9
```
To make the tests pass we should strip the `/private` prefix on MacOS, if it exists.
It shouldn't be an issue since MacOS provides a `/var` symlink to mimic Unix behaviour

radicle: Fix profile::canonicalize_home test on MacOS

---

radicle-httpd/src/api/v1/projects.rs
radicle-httpd/src/test.rs
radicle/src/cob/patch.rs

Adds the endpoint `PATCH /projects/:project/patches/:id` to the `radicle-httpd`
This endpoint allows:
- editing title, description and target
- edit tags
- add revisions
- add a review
- add a merge
- create discussions threads and replies
This PR also adds a few tests to test these new features.

radicle-httpd: Add patch update endpoint

---

radicle-httpd/src/raw.rs

This PR adds the following headers to the `/raw` endpoint, they are similar to the `api` router.
Most importantly we need to `Access-Control-Allow-Origin` so we can query the endpoint from the web client.
- `Access-Control-Max-Age` of 24 hours, so we cache some of the requests.
- We should probably implement something that caches even longer
- `Access-Control-Allow-Origin` so we can do `fetch` from the web client to this endpoint without cors issues
- `Access-Control-Allow-Methods` so we limit the allowed methods to GET
- `Access-Control-Allow-Methods` limit to `content-type` so we can require application/json, etc.

httpd: Add `CorsLayer` to `/raw` endpoint

---

radicle-httpd/src/api/v1/projects.rs
radicle/src/cob/patch.rs

For the web client to be able to show file content based on a Oid we need to provide the web client with the file in question.
~~It gets a bit messy IMO, since we need to drill down until we get to the `CodeLocation` to be able to serialize the Blob Oid, into its content, adding a new field..~~
~~I think this would be nicer if instead or additionally to passing a Blob Id we store the file path in the `CodeLocation` struct, and then query the `/raw` endpoint for the files content.~~

httpd: Add `content` property to `CodeLocation` in serialization

---

radicle-cli/src/commands/tag.rs
radicle-cli/src/commands/untag.rs

Whats on the tin.
Instead of just allowing issues to be tagged and untagged, we should also allow patches to be tagged.

cli: Enable `rad tag` and `rad untag` for patches as well

---

radicle-httpd/src/api/json.rs
radicle-httpd/src/api/v1/projects.rs

This PR adds the `RefStrings` of the branches that have the patch head.

httpd: Add patch head branches to patch output

---

radicle-httpd/src/api/json.rs
radicle-httpd/src/api/v1/projects.rs
radicle/src/cob/issue.rs

This PR adds the reactions array to `json::issue` and `json::patch` output.
**Remarks**
- @FintanH I made the `cob::issue::Issue` properties public, similar to `cob::patch::Patch`, if we don't want to do that, maybe I can find a workaround to get the `thread` property some other way..

httpd: Add reactions to issue and patch json output

---

radicle-node/src/tests/e2e.rs
radicle-node/src/worker.rs
radicle/src/identity/doc.rs
radicle/src/rad.rs
radicle/src/storage.rs
radicle/src/storage/git.rs
radicle/src/test/storage.rs

Introduce a canonical reference for refs/rad/id to aid in discovering
information about a repository without knowing a peer -- e.g. if a
peer wants to clone a new repository it needs to find out which peers
are delegates for that project, but does not know what their NIDs are
up front.
The approach mirrors the canonical `head` for a repository and
introduces useful constructors for `Doc`/`DocAt`.

Canonical `refs/rad/id`

---

radicle-httpd/src/api/v1/delegates.rs
radicle-httpd/src/api/v1/projects.rs
radicle/src/cob/patch.rs

This allows the httpd to receive PATCH methods and update the lifecycle of a patch.
BREAKING:
This changes the patch state proposed to open, which will probably break some of the currently created patches.

Add patch lifecycle

---

radicle-crypto/src/lib.rs
radicle-node/src/runtime.rs
radicle-node/src/tests/e2e.rs
radicle-node/src/worker.rs
radicle-node/src/worker/fetch.rs
radicle-node/src/worker/fetch/error.rs
radicle-node/src/worker/fetch/refspecs.rs
radicle/src/git.rs

The previous fetching logic had some pitfalls regarding its logic:
* Fetched 'rad' references could end up not being verifiable and leaving the storage in a corrupt state
* Forced pushes would be prohibited, since they would be rejected by the client side due to the refspecs being used.
The new approach is to stage a fetch in 2 steps. The first step is to fetch the relevant `rad/id` and `rad/sigrefs` for verification. For all remotes that are verified, fetch all references listed in their respective `rad/sigrefs`, using the `+` marker in the refspec, allowing to update for any force pushes -- note that this becomes a safe operation since the `sigrefs` are signed by the remote that created them.
To prevent unverifiable 'rad' references from polluting storage, all fetch negotiations are …

node: multistep fetching logic

---

radicle-node/src/service.rs
radicle-node/src/service/tracking.rs
radicle-node/src/test/simulator.rs
radicle-node/src/tests/e2e.rs
radicle-node/src/worker/fetch.rs
radicle-node/src/worker/fetch/refspecs.rs
radicle/src/storage.rs

When a repository does not yet exist during a fetch, i.e. a clone, then only delegates are being fetched.
Augment Namespaces::Many to hold the trusted and optional delegate peers separately. Doing so allows the construction of the variant without the repository existing, but tracking relationships existing.
This variant can then be used to build refspecs for both the trusted peers and delegates when doing a cloning fetch.

node: fetch trusted peers on clone

---

radicle-cli/src/commands/merge.rs
radicle-cli/src/commands/patch/checkout.rs
radicle-cli/src/commands/patch/common.rs
radicle-cli/src/commands/patch/list.rs
radicle-cli/src/commands/patch/update.rs
radicle-httpd/src/api/json.rs
radicle/src/cob/patch.rs

Replaces pub accessors to struct fields with methods.
Also creates some methods to compute necessary information
As talked about here https://github.com/radicle-dev/heartwood/pull/479#issuecomment-1482503388
and here https://github.com/radicle-dev/heartwood/pull/479#issuecomment-1482731408
There are also other places where we eventually could reduce public exposure, but one PR at a time

Reduce pub accessors in patch and issue cob structs

---

radicle/src/cob/identity.rs
radicle/src/rad.rs
radicle/src/storage/git.rs

We were recomputing the `rad/id` ref every time it was accessed.
@FintanH any idea why the `rad-id.md` tests fail? Seems like there's some discrepancy between the cached and canonical ref, which makes me think we aren't setting the ref in some crucial place during `rad id`?

Use cached canonical `rad/id` refs

---

radicle-node/src/service.rs
radicle/src/node/routing.rs
radicle/src/node/tracking/store.rs

This fixes an issue that came up in tests where we would be reading and writing to the database at the same time, and it would fail with an error due to the lock being contended on.

node: Make sure we retry on lock contention

---

radicle-crdt/src/lwwreg.rs
radicle/src/cob/identity.rs
radicle/src/cob/issue.rs
radicle/src/cob/patch.rs

Using LWWReg::from will always set the clock value to the default, which can end up being used wrong.
Instead, introduce a constructor method `initial` to indicate that it should be used on initial construction, while `new` should be used for newer values of the register.
Fixes #496

radicle: force new or initial construction of LWWReg

---

scripts/install

Downloads binaries and installs them, based on your operating system.
Can be used in a one liner, for example:
sh <(curl https://radicle.xyz/install)
Depends on #514

Add `install` script

---

radicle-tui/src/app.rs
radicle-tui/src/lib.rs
radicle-tui/src/ui.rs
radicle-tui/src/ui/components/workspace.rs
radicle-tui/src/ui/layout.rs

- add a `not implemented` placeholder label to the `issues` tab
- bring back initial message polling (`PollStrategy::Once`), but only re-render UI if needed
- move shortcuts widget to root widget (e.g. dashboard, patch browser etc.) in order to show widget-dependent shortcuts

tui: UX improvements

---

radicle-cli/examples/rad-fetch.md
radicle-cli/examples/rad-fork.md
radicle-cli/src/commands.rs
radicle-cli/src/commands/fork.rs
radicle-cli/src/commands/help.rs
radicle-cli/src/commands/inspect.rs
radicle-cli/src/main.rs
radicle-cli/tests/commands.rs

Add a `rad fork` command to create a forked namespace, using the local peer, for the given repository.

cli: add rad fork command
