radicle-dev/heartwood

radicle-node/src/service.rs, radicle-node/src/service/message.rs, radicle-node/src/service/reactor.rs, radicle-node/src/test.rs, radicle-node/src/test/arbitrary.rs, radicle-node/src/test/gossip.rs, radicle-node/src/test/peer.rs, radicle-node/src/test/tests.rs, radicle-node/src/wire/message.rs
=> Rebroadcast logic for stored gossip messages

radicle-node/src/client/handle.rs, radicle-node/src/control.rs, radicle-node/src/service.rs, radicle-node/src/service/peer.rs, radicle-node/src/test/handle.rs, radicle-node/src/test/tests.rs
Useful mostly for debugging, or creating some nice dashboards.
=> Add commnads to query internal service state

radicle-node/src/service.rs, radicle-node/src/service/message.rs, radicle-node/src/test/arbitrary.rs, radicle-node/src/wire.rs, radicle/src/node.rs, radicle/src/node/features.rs
=> Implement proper `NodeFeatures` type

radicle-node/src/service.rs, radicle-node/src/test/peer.rs, radicle-node/src/test/tests.rs
Since we now have three announcement message types, we need at least three timestamps per peer. But even that is not enough, since we don't want to conflate ref announcements for different projects with each other.
The solution is to also keep a map of timestamps per peer, for each tracked project. That way we are able to know when a ref announcement is interesting to us or not.
Closes #44
=> Correct handling of announcement timestamps

radicle-node/src/service.rs, radicle-node/src/service/message.rs, radicle-node/src/test/peer.rs, radicle-node/src/test/simulator.rs, radicle-node/src/test/tests.rs
Closes #24 
Final work to close #24.
=> Refs announcement tests

radicle-node/src/service.rs, radicle-node/src/service/message.rs, radicle-node/src/service/peer.rs, radicle-node/src/test/arbitrary.rs, radicle-node/src/test/tests.rs, radicle-node/src/wire/message.rs
=> Enforce max size for `Message` type on wire

radicle-node/src/client.rs, radicle-node/src/control.rs, radicle-node/src/main.rs, radicle-node/src/service/routing/schema.sql, radicle-remote-helper/src/lib.rs, radicle-tools/src/rad-push.rs, radicle/src/git.rs, radicle/src/profile.rs, radicle/src/rad.rs, radicle/src/storage.rs, radicle/src/storage/git.rs, radicle/src/storage/git/transport.rs, radicle/src/storage/git/transport/url.rs, radicle/src/test/storage.rs
Fixing various TODOs and long standing issues.
Might be easier to review commit-by-commit.
=> Fix various issues

radicle-node/src/service.rs
Its easy to confuse what/who 'node' or 'session' is.  Make the primary node 'from' to make it consistent with process_inventory.  Rename the announcement's node to 'announcer', clarifying its source.
=> radicle-node: better distinguish nodes in handle_announcement

Cargo.lock, radicle-node/Cargo.toml
Enable Radicle Crypto's test feature.
Fixes #76
=> node: fix test dependency error

Cargo.lock, radicle-crypto/Cargo.toml, radicle-crypto/src/lib.rs, radicle-crypto/src/ssh.rs, radicle-crypto/src/ssh/agent.rs, radicle-crypto/src/ssh/keystore.rs, radicle-crypto/src/test/arbitrary.rs, radicle-crypto/src/test/signer.rs, radicle-node/src/main.rs, radicle-tools/src/rad-agent.rs
Closes #79 
I opted for Zeroize for the passphrase because (1) it's already a dependency, and (2) it seems to do the same thing
=> Zeroize all the things

Cargo.lock, Cargo.toml, radicle-cli/Cargo.toml, radicle-cli/src/lib.rs, radicle-cli/src/terminal.rs, radicle-cli/src/terminal/args.rs, radicle-cli/src/terminal/command.rs, radicle-cli/src/terminal/format.rs, radicle-cli/src/terminal/io.rs, radicle-cli/src/terminal/patch.rs, radicle-cli/src/terminal/spinner.rs, radicle-cli/src/terminal/table.rs, radicle-cli/src/terminal/textbox.rs, radicle-node/src/service.rs, radicle/src/node.rs
First step in starting to port some of the CLI code over.
=> Add `radicle-cli` crate's `terminal` module

Cargo.lock, radicle-cli/Cargo.toml, radicle-cli/src/commands.rs, radicle-cli/src/commands/checkout.rs, radicle-cli/src/commands/init.rs, radicle-cli/src/git.rs, radicle-cli/src/lib.rs, radicle-cli/src/project.rs, radicle-node/src/test/tests.rs, radicle-tools/src/rad-init.rs, radicle/src/lib.rs, radicle/src/rad.rs, radicle/src/storage/git.rs, radicle/src/test/fixtures.rs
=> Add `rad-init`, `rad-checkout` commands

Cargo.lock, radicle-crypto/Cargo.toml, radicle-crypto/src/lib.rs, radicle-node/Cargo.toml, radicle-node/src/address/store.rs, radicle-node/src/lib.rs, radicle-node/src/service/routing.rs, radicle-node/src/sql.rs, radicle/Cargo.toml
=> Update `sqlite` dependency & add transactionality

radicle-cli/src/commands.rs, radicle-cli/src/commands/push.rs, radicle-cli/src/git.rs, radicle/src/git.rs
=> Implement `rad-push`

CONTRIBUTING.md, DCO, LICENSE-APACHE, LICENSE-MIT
Taken from other repos with some small edits.
=> Add licenses and contributor information

radicle-cli/src/commands.rs, radicle-cli/src/commands/review.rs
=> Add `rad-review` command

radicle-cli/src/commands.rs, radicle-cli/src/commands/merge.rs, radicle-cli/src/terminal/format.rs
=> Add `rad-merge` command

radicle-node/src/bounded.rs
Borrow documentation from Rusts standard library to document BoundedVec's functions, and add documentation tests where appropriate.
And make it's deref trait return a slice instead of a Vec, which is more common in rust.
Signed-off-by: Slack Coder <slackcoder@server.ky>
=> node: Document and test BoundedVec

radicle-cli/src/terminal/format.rs, radicle-cob/src/backend/git/change.rs, radicle-cob/src/change/store.rs, radicle-cob/src/change_graph/evaluation.rs, radicle-cob/src/history.rs, radicle-cob/src/history/entry.rs, radicle-cob/src/object/collaboration/create.rs, radicle-cob/src/object/collaboration/update.rs, radicle-crdt/src/change.rs, radicle-crdt/src/clock.rs, radicle/src/cob.rs, radicle/src/cob/common.rs, radicle/src/cob/issue.rs, radicle/src/cob/patch.rs, radicle/src/cob/thread.rs
=> COB Timestamps

Cargo.lock, radicle-cob/src/lib.rs, radicle-cob/src/object.rs, radicle-cob/src/object/collaboration/list.rs, radicle-crdt/Cargo.toml, radicle-crdt/src/change.rs, radicle-crdt/src/gmap.rs, radicle-crdt/src/lib.rs, radicle-crdt/src/lwwmap.rs, radicle-crdt/src/lwwreg.rs, radicle-crdt/src/ord.rs, radicle/src/cob.rs, radicle/src/cob/change.rs, radicle/src/cob/issue.rs, radicle/src/cob/op.rs, radicle/src/cob/patch.rs, radicle/src/cob/store.rs, radicle/src/cob/thread.rs
=> Some CRDT improvements and COB cleanups

radicle/src/cob/issue.rs, radicle/src/cob/op.rs, radicle/src/cob/patch.rs, radicle/src/cob/thread.rs
=> Fix JSON serialization for COB operations

radicle-crypto/src/lib.rs, radicle-crypto/src/ssh/keystore.rs
=> crypto: Add ECDH trait and `MemorySigner` impl

radicle-node/src/test/peer.rs, radicle-node/src/tests.rs
Fix the test for pruning a node's inventory which inconsistently and rarely fails.  It fails due to each test peers' clocks being slightly out of sync in the test.  One peer may have their clock skewed one second before the other.
The test confirms how pruning inventory entries relates to time.  Time therefor needs to be accurate to test against internal edge cases.
Note:
I would prefer to sync the clocks manually, the alternative of using an 'if' and 'elapsed' combination seems a bit much.
i.e.
```
bob.clock().set(alice.clock().local_time());
```
=> node: fix inconsistently failing test

radicle-cob/src/change_graph/evaluation.rs, radicle-cob/src/history.rs, radicle-crdt/src/clock.rs, radicle/src/cob/issue.rs, radicle/src/cob/patch.rs, radicle/src/cob/store.rs, radicle/src/cob/thread.rs
See commits.
@FintanH we forgot to set the clock correctly in the previous change, so have a look at that.
=> Use the new COB batching capabilities

radicle-cli/src/terminal/io.rs, radicle-httpd/src/api/v1/projects.rs, radicle/src/cob/issue.rs, radicle/src/cob/patch.rs, radicle/src/cob/thread.rs
Functionality for comment editing in threads.
=> Comment editing

radicle-cli/src/commands/self.rs, radicle-cli/src/terminal/table.rs
Add a little documentation and make it easier to use by accepting `&str` over `String`.
=> Improve terminal's Table

radicle-cli/examples/rad-issue.md, radicle-cli/src/commands/issue.rs
Add support for listing a users assigned issue via 'issue list', and show issue information with 'issue show <issue id>'
These changes depend on the earlier pull request (https://github.com/radicle-dev/heartwood/pull/159)
=> List your issues using 'issue list' and show issue info via 'issue show'

radicle-cli/src/commands/auth.rs, radicle-cli/tests/commands.rs, radicle-crypto/src/lib.rs, radicle-crypto/src/ssh.rs, radicle-crypto/src/ssh/keystore.rs, radicle-tools/src/rad-auth.rs, radicle/src/profile.rs
Some of this we need to implement a conversion tool between link and heartwood keys.
=> Crypto-related updates

radicle-cob/src/backend/git/change.rs, radicle-cob/src/change.rs, radicle-cob/src/change/store.rs, radicle-cob/src/lib.rs, radicle-cob/src/object/collaboration/create.rs, radicle-cob/src/object/collaboration/update.rs, radicle-cob/src/test/storage.rs, radicle-httpd/src/api/v1/projects.rs, radicle/src/cob/issue.rs, radicle/src/cob/op.rs, radicle/src/cob/patch.rs, radicle/src/cob/store.rs, radicle/src/cob/thread.rs, radicle/src/storage/git.rs, radicle/src/storage/git/cob.rs
Some renames that were discussed, plus a new `OpId` type that is safer.
=> Tidy up some COB things

radicle-cob/src/change_graph/evaluation.rs, radicle-cob/src/history.rs, radicle-cob/src/history/entry.rs, radicle-dag/src/lib.rs, radicle/src/cob.rs, radicle/src/cob/issue.rs, radicle/src/cob/op.rs, radicle/src/cob/patch.rs, radicle/src/cob/store.rs, radicle/src/cob/test.rs, radicle/src/cob/thread.rs
A few changes are made to make testing history permutations possible, and then the first test of that kind is written.
See individual commits for more detail.
=> Setup for testing history permutations

radicle-cli/examples/rad-issue.md, radicle-cli/src/commands/issue.rs
* Use an `--assigned` flag
* Default to listing all issues
Signed-off-by: Alexis Sellier <self@cloudhead.io>
=> cli: Make some changes to issue listing

Cargo.lock, Cargo.toml, radicle-crypto/src/lib.rs, radicle-crypto/src/test/signer.rs, radicle-node/Cargo.toml, radicle-node/src/client/handle.rs, radicle-node/src/lib.rs, radicle-node/src/main.rs, radicle-node/src/service.rs, radicle-node/src/service/message.rs, radicle-node/src/service/reactor.rs, radicle-node/src/service/session.rs, radicle-node/src/test/peer.rs, radicle-node/src/test/simulator.rs, radicle-node/src/wire/message.rs, radicle-node/src/wire/transport.rs, radicle-node/src/worker.rs, radicle/src/storage.rs
Also implements listener behavior.
Supercedes #175 
=> node: Implement worker thread handover

Cargo.lock, radicle-node/src/wire/transport.rs, radicle-node/src/worker.rs
=> node: Update io-reactor

radicle-cli/examples/rad-init.md, radicle-cli/src/commands/edit.rs, radicle-cli/src/commands/init.rs, radicle-cli/src/commands/inspect.rs, radicle-cli/src/terminal/io.rs
Fix order of iteration, and make output look more like commit log. Also show commit parent and message.
=> cli: Update `inspect` command

radicle-node/src/service.rs, radicle-node/src/service/session.rs
We shouldn't be marking attempted peers as "connected". We should wait for the connection to be properly established.
=> node: Fix attempted session state

radicle-node/src/tests/e2e.rs, radicle-node/src/worker.rs
Fix all of the `FIXME` in the worker.
Signed-off-by: Alexis Sellier <self@cloudhead.io>
=> node: Properly parse replication data

Cargo.lock, Cargo.toml, radicle-httpd/Cargo.toml, radicle-httpd/src/api.rs, radicle-httpd/src/api/error.rs, radicle-httpd/src/api/json.rs, radicle-httpd/src/api/v1/projects.rs
This is to play around the new `radicle-surf` API and see if it can meet the existing user's needs. The goal is to seek feedbacks, not only about the usages in the diff, but also about what is not covered but necessary.
=> dogfood the new radicle-surf API

radicle-node/src/client.rs, radicle-node/src/client/handle.rs, radicle-node/src/control.rs, radicle-node/src/test/logger.rs, radicle-node/src/tests/e2e.rs, radicle-node/src/worker.rs
=> node: Implement graceful shutdown

radicle-cli/examples/rad-issue.md, radicle-cli/src/commands.rs, radicle-cli/src/commands/comment.rs, radicle-cli/src/main.rs
Allow users to comment on an Issue.
References: #187
=> cli: Add minimal `rad comment`

.github/workflows/frontend-testing.yml
This is to facilitate testing on dev’s machines.
=> Upload macOS binaries for e2e testing

radicle-cli/examples/rad-patch.md, radicle-cli/src/commands/patch.rs, radicle-cli/src/commands/patch/create.rs, radicle-cli/src/commands/patch/show.rs, radicle-cli/src/terminal.rs, radicle-cli/src/terminal/cob.rs, radicle-cli/src/terminal/patch.rs
Show patch information with `rad patch show`.
References #148
=> cli: add `rad patch show`

radicle-cli/tests/commands.rs, radicle-crypto/src/lib.rs, radicle-httpd/src/api/test.rs
The latter is strictly more powerful.
=> Replace `RAD_DEBUG` with `RAD_SEED`

radicle-node/src/client.rs, radicle-node/src/control.rs, radicle-node/src/logger.rs, radicle-node/src/main.rs, radicle-node/src/service.rs
=> node: Improve logging output

radicle-node/src/service.rs, radicle-node/src/service/reactor.rs, radicle-node/src/worker.rs
We were not properly exiting one of the threads that was copying data from the stream to the upload-pack process. This is a fix.
=> node: Fix bug in upload-pack

Cargo.lock, Cargo.toml, radicle-httpd/Cargo.toml, radicle-httpd/src/api/json.rs
Pending https://github.com/radicle-dev/radicle-git/pull/104 merge.
=> Update `radicle-surf` to `755124dab39548efe3a40a426bbca5e6404cd2fd`

.github/workflows/release.yml
Continuation of https://github.com/radicle-dev/heartwood/pull/250 but for the release jobs this time.
=> Switch to maintained GitHub actions

radicle-httpd/src/api/v1/sessions.rs
To allow the web client to remove a session if requested by the user, we should remove the entry represented by the `session_id`.
New added route:
`DELETE /sessions/:id`
Things to talk about:
=> radicle-httpd: Add DELETE route to remove sessions

radicle-cli/examples/rad-clone-unknown.md, radicle-cli/examples/rad-clone.md, radicle-cli/examples/rad-init-announce-refs.md, radicle-cli/examples/rad-init.md, radicle-cli/src/commands/clone.rs, radicle-cli/src/commands/init.rs, radicle-cli/src/terminal/io.rs, radicle-cli/src/terminal/spinner.rs, radicle-cli/tests/commands.rs, radicle-cli/tests/framework/mod.rs, radicle-httpd/src/api/test.rs, radicle-node/src/service.rs
=> Announce refs on `rad init`

radicle-cli/examples/rad-clone.md, radicle-cli/tests/commands.rs, radicle-node/src/test/environment.rs
The last commit of a newly cloned repository should remain untouched.
=> cli: Test rad-clone is deterministic

radicle-cli/src/commands/web.rs
This also adds an informative text instructing the user what clicking the link does and improves the CLI argument names.
If no arguments are passed point the user to the production web app at https://app.radicle.xyz.
=> cli: Allow specifying protocol for `rad web` frontend

Cargo.lock, radicle-cli/examples/rad-init-sync.md, radicle-cli/examples/rad-init.md, radicle-cli/src/commands/clone.rs, radicle-cli/src/commands/init.rs, radicle-cli/tests/commands.rs, radicle-httpd/src/api/test.rs, radicle-node/Cargo.toml, radicle-node/src/control.rs, radicle-node/src/runtime.rs, radicle-node/src/runtime/handle.rs, radicle-node/src/service.rs, radicle-node/src/service/config.rs, radicle-node/src/service/session.rs, radicle-node/src/service/tracking.rs, radicle-node/src/service/tracking/store.rs, radicle-node/src/test/environment.rs, radicle-node/src/test/gossip.rs, radicle-node/src/test/handle.rs, radicle-node/src/test/peer.rs, radicle-node/src/test/simulator.rs, radicle-node/src/tests.rs, radicle/src/node.rs, radicle/src/storage.rs, radicle/src/storage/git.rs, radicle/src/test/storage.rs
=> Replication issues and other things

radicle-cli/examples/rad-id-rebase.md, radicle-cli/examples/rad-id.md, radicle-cli/src/commands/id.rs, radicle/src/identity/doc.rs
=> Output Identity SHA

radicle-node/src/runtime.rs
If the socket file is deleted while the node is running, we can no longer quit with Ctrl-C. This is the "fix".
Fixes #307
=> node: Fix bug when socket file is deleted

radicle-node/src/service.rs, radicle-node/src/service/reactor.rs, radicle-node/src/tests.rs
=> node: Subscribe on track-repo

Cargo.lock, radicle-cli-test/Cargo.toml, radicle-cli-test/README.md
Required for cargo to accept the crate.
=> cli-test: Complete cargo metadata

Cargo.lock, radicle-httpd/Cargo.toml, radicle-httpd/src/api.rs, radicle-httpd/src/api/v1/delegates.rs, radicle-httpd/src/api/v1/projects.rs, radicle-httpd/src/api/v1/sessions.rs, radicle-httpd/src/api/v1/stats.rs, radicle-httpd/src/error.rs, radicle-httpd/src/git.rs, radicle-httpd/src/lib.rs, radicle-httpd/src/test.rs
Fixes https://github.com/radicle-dev/heartwood/issues/332
=> httpd: Change `500` into `404` when project doesn't exist

radicle-node/src/main.rs, radicle-node/src/runtime.rs, radicle-node/src/service/config.rs, radicle-node/src/service/tracking.rs
Sets the default tracking policy.
=> node: Add `--tracking-policy` flag

radicle-cli/src/commands/clone.rs, radicle-cli/tests/commands.rs, radicle-node/src/test/environment.rs, radicle/src/rad.rs
=> cli: Don't fail clone if we have repo locally

radicle-cli/examples/rad-inspect.md, radicle-cli/src/commands.rs, radicle-cli/src/commands/clone.rs, radicle-cli/src/commands/fetch.rs, radicle-cli/src/commands/help.rs, radicle-cli/src/commands/patch.rs, radicle-cli/src/commands/patch/create.rs, radicle-cli/src/commands/patch/list.rs, radicle-cli/src/commands/patch/update.rs, radicle-cli/src/terminal/args.rs, radicle/src/cob/store.rs, radicle/src/node.rs
`rad fetch` fetches refs from seeds, for the given project.
=> `rad fetch`

radicle-cli/src/commands/assign.rs, radicle-cli/src/commands/comment.rs, radicle-cli/src/commands/id.rs, radicle-cli/src/commands/issue.rs, radicle-cli/src/commands/merge.rs, radicle-cli/src/commands/patch.rs, radicle-cli/src/commands/patch/checkout.rs, radicle-cli/src/commands/patch/common.rs, radicle-cli/src/commands/patch/create.rs, radicle-cli/src/commands/patch/list.rs, radicle-cli/src/commands/patch/show.rs, radicle-cli/src/commands/patch/update.rs, radicle-cli/src/commands/review.rs, radicle-cli/src/commands/unassign.rs, radicle-httpd/src/api.rs, radicle-httpd/src/api/v1/delegates.rs, radicle-httpd/src/api/v1/projects.rs, radicle-httpd/src/test.rs, radicle/src/cob/identity.rs, radicle/src/cob/issue.rs, radicle/src/cob/patch.rs, radicle/src/cob/store.rs, radicle/src/storage/git.rs
=> Sign COBs, simplify use

radicle-cli/examples/rad-node.md, radicle-cli/src/commands.rs, radicle-cli/src/commands/help.rs, radicle-cli/src/commands/node.rs, radicle-cli/src/commands/node/control.rs, radicle-cli/src/commands/node/routing.rs, radicle-cli/src/commands/node/tracking.rs, radicle-cli/src/main.rs, radicle-cli/src/terminal/args.rs, radicle-cli/tests/commands.rs, radicle-node/src/control.rs, radicle-node/src/runtime/handle.rs, radicle-node/src/service.rs, radicle-node/src/service/tracking.rs, radicle-node/src/service/tracking/store.rs, radicle-node/src/test/handle.rs, radicle/src/node.rs, radicle/src/node/tracking.rs
See the commits for more detail on the changes.
@cloudhead the `start` and `stop` commands are still a bit fuzzy for me. I'm not sure how they're expected to work :thinking:
=> `rad node`

radicle-cli/tests/commands.rs, radicle-node/src/service.rs, radicle-node/src/service/reactor.rs, radicle-node/src/service/session.rs
=> Node replication fixes

radicle-httpd/Cargo.toml, radicle-httpd/src/api/v1/projects.rs, radicle-httpd/src/test.rs
As you can see in test cases, this doesn't change other stuff much. Maybe I should manually remove the one hosted by seed on-disk?
=> httpd: Run tests off another remote than seed

radicle-cli/examples/rad-patch.md, radicle-cli/src/commands/patch.rs, radicle-cli/src/commands/patch/common.rs, radicle-cli/src/commands/patch/create.rs, radicle-cli/src/commands/patch/show.rs, radicle-cli/src/commands/patch/update.rs, radicle-cli/src/terminal/patch.rs, radicle-tools/src/rad-cli-demo.rs
Cleanup and simplify output of patch command. Closes #387
=> cli: Improve `patch` command

radicle-node/src/runtime.rs
This avoids race conditions, especially in tests, where we try to connect to the node right after spawning it, but since the `Runtime::run` function is often called in a different thread, the socket is not created in time.
=> node: Bind control socket immediately

radicle-node/src/main.rs
The radicle-node was forced into using Scope::Trusted for its default scope.
Allow the Scope to be specified at the command line using a `--tracking-scope` option.
=> radicle-node: add tracking-scope option

Cargo.lock, radicle-cli/Cargo.toml, radicle-cli/examples/rad-issue.md, radicle-cli/src/commands/assign.rs, radicle-cli/src/commands/unassign.rs
Just some code and ux improvements.
=> cli: Polish `assign` and `unassign` commands

radicle-node/src/service.rs, radicle-node/src/service/session.rs, radicle-node/src/test/peer.rs, radicle-node/src/tests.rs, radicle-node/src/wire/protocol.rs
=> node: Fix reconnection logic

radicle-cli/examples/rad-auth.md, radicle-cli/examples/rad-self.md, radicle-cli/src/commands/self.rs, radicle-cli/tests/commands.rs
=> cli: Flesh out `rad self`

radicle-node/src/wire/protocol.rs
Due to never removing peers from the peer map in the wire protocol module, it was possible for there to be multiple connected peers with the same Node ID. Some might be in a "connected" state, while others might be "disconnected".
This caused a bug where a peer, although connected would be considered disconnected by the wire module, because when searching for a peer with that Node ID, the disconnected one would return first.
To fix this, we make sure to remove peers from the map once the connection is dropped.
=> node: Fix state mismatch between service and wire

radicle-node/src/runtime.rs, radicle-node/src/runtime/handle.rs, radicle-node/src/service.rs, radicle-node/src/service/reactor.rs, radicle-node/src/test/peer.rs, radicle-node/src/test/simulator.rs, radicle-node/src/tests.rs, radicle-node/src/wire/protocol.rs
Context: https://radicle.zulipchat.com/#narrow/stream/369277-heartwood/topic/Emitting.20events.20from.20.60node.60
=> node: Add eventing system to handler

radicle-httpd/src/api/v1/projects.rs, radicle-httpd/src/test.rs
Adds a `diff` endpoint to get the diff and commit listing between two commits.
Very useful for patches, but eventually also for other places.
Pending:
=> radicle-httpd: Add commit diff endpoint

radicle-node/src/service.rs, radicle-node/src/service/session.rs, radicle-node/src/tests.rs, radicle/src/test/arbitrary.rs
=> radicle-node: Queue fetch requests when necessary

radicle-node/src/test/logger.rs, radicle-node/src/worker.rs
=> Improve worker error handling

radicle/src/storage.rs, radicle/src/storage/git.rs
=> Skip hidden files in repository listing (`rad ls`)

radicle-node/src/service.rs
1. We were announcing inventory every 30 seconds. This is now changed to 1 hour.
2. We were using a variable to track whether our inventory has been announced to the network, but this var was set based on what we tracked, not the inventory we had. This var has been removed.
=> node: Fix periodic inventory announcement

radicle-node/src/service.rs, radicle-node/src/service/session.rs, radicle-node/src/test/peer.rs, radicle-node/src/test/simulator.rs, radicle-node/src/tests.rs, radicle-node/src/wire/protocol.rs
=> Fix some node re-connection issues

radicle-node/src/service.rs
We were not correctly deleting the fetch request, since only one was kept per RID.
=> node: Fix fetch requests code

radicle-node/src/service.rs, radicle-node/src/test/peer.rs, radicle-node/src/tests.rs, radicle/src/test/storage.rs
This is to solve issue #316 
For the design considerations history, please see https://github.com/radicle-dev/heartwood/pull/370#discussion_r1133476801
=> radicle-node: fetch refs only if tracking the node

radicle-cli/examples/rad-node.md, radicle-cli/examples/rad-patch.md, radicle-cli/examples/workflow/4-patching-contributor.md, radicle-cli/src/commands/node/routing.rs, radicle-cli/src/commands/node/tracking.rs, radicle-term/src/cell.rs, radicle-term/src/element.rs, radicle-term/src/lib.rs, radicle-term/src/table.rs
Making tables look nicer; see examples.
=> term: Add border support for tables

radicle/src/cob/patch.rs
Using `LWWReg::from` was giving subsequent actions the same `clock` value as their predecessors.
This resulted in a `Reject` not being able to turn into an `Accept` on a second review of a patch.
The solution is to use the `clock` value that was produced for the `Op` and pass that into new, avoiding the call to `from`.
=> cob: Use `LWWReg::new` instead of `LWWReg::from` in `Review::new`

.env.seed, HACKING.md, radicle-cli/examples/rad-auth.md, radicle-cli/src/commands/self.rs, radicle-node/src/main.rs, radicle/src/node.rs, radicle/src/profile.rs
=> node: Add --force option to start node 

radicle-node/src/tests/e2e.rs, radicle-node/src/worker/fetch.rs
Owned refs were being pruned on fetch.
=> node: Don't prune owned refs

radicle-cli/src/commands/issue.rs, radicle/src/cob/store.rs
I found this while working on my project today!
See commits for more details
=> cli: Show a message when there are no issues to display

radicle-cli/examples/rad-issue.md, radicle-cli/examples/rad-patch-draft.md, radicle-cli/examples/rad-tag.md, radicle-cli/examples/workflow/3-issues.md, radicle-cli/src/commands/comment.rs, radicle-cli/src/commands/issue.rs, radicle-cli/src/commands/patch.rs, radicle-cli/src/commands/patch/create.rs, radicle-cli/src/commands/patch/ready.rs, radicle-cli/src/commands/patch/update.rs, radicle-cli/src/commands/review.rs, radicle-cli/src/terminal/patch.rs, radicle-cli/tests/commands.rs, radicle-node/src/wire/protocol.rs, radicle-node/src/worker/channels.rs, radicle/src/cob/issue.rs, radicle/src/cob/patch.rs, scripts/delete-remote-refs.sh, scripts/patch-rebase.sh, scripts/show-sigrefs.sh
=> cli: show the issue in a better way
